name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to your main branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Ensure you have tests defined in your package.json

      - name: Build Docker image
        run: docker build . -t my-node-app

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-node-app myusername/my-node-app:latest  # Replace with your Docker Hub username
